import { Database } from "bun:sqlite";
import { runSuiteAnyLanguage } from "./src/server/grading.ts";
const db = new Database("data/prep.db", { readonly: true });
const [slug, lang, file] = [process.argv[2]!, process.argv[3]!, process.argv[4]!];
const s = db.query<{ io_cases: string }, [string]>("SELECT io_cases FROM full_tests WHERE slug = ?").get(slug)!;
const m = db.query<{ meta_json: string | null }, [string]>("SELECT meta_json FROM problems WHERE slug = ?").get(slug);
const meta = m?.meta_json ? JSON.parse(m.meta_json) : null;
const code = await Bun.file(file).text();
const r = await runSuiteAnyLanguage({ slug, code, fnName: meta?.name ?? "", ioJson: s.io_cases, meta, language: lang });
console.log(JSON.stringify({ lang, accepted: r.accepted, passed: r.passed, total: r.total, ungradeable: r.ungradeable, firstErr: r.cases[0]?.error, stderr: r.stderr?.slice(0,400) }, null, 2));
